export const KEY_CHOOSE_SOMETHING = {
  SELL_SOMETHING: 'SELL',
  BUY_SOMETHING: 'BUY',
}

export const PRICE_CURRENCY = {
  USD: 'USD',
  VND: 'VND'
}

export const KEY_CHOOSE_DELIVERY = {
  SUPPORTEDDELIVERY: 'SUPPORTEDDELIVERY',
  NOTSUPPORTEDDELIVERY: 'NOTSUPPORTEDDELIVERY'
}

export const ACTION_CHAT = {
  CONFIRM_DEAL: 'confirm_deal',
  ENTER_PRICE: 'enter_price',
  ENTER_PHONE: 'enter_phone'
}