export const KEY_CHOOSE_SOMETHING = {
  SELL_SOMETHING: 'SELL',
  BUY_SOMETHING: 'BUY',
}

export const PRICE_CURRENCY = {
  USD: 'USD',
  VND: 'VND'
}

export const ACTION_CHAT = {
  CONFIRM_DEAL: 'CONFIRM_DEAL',
  CONFIRM_PRICE: 'CONFIRM_PRICE'
}